[build]
  # 构建命令（静态网站，无需构建）
  command = ""
  
  # 发布目录
  publish = "."
  
  # 环境变量（可选）
  [build.environment]
    NODE_VERSION = "18"

# 重定向规则（单页应用）
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 头部设置
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
